
services:
  # base de datos
  postgres:
    image: postgres:16-alpine
    container_name: contrato_DB
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=simtexx_user
      - POSTGRES_PASSWORD=simtexx_pass
      - POSTGRES_DB=simtexx_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Interfaz gr√°fica para monitorear BD

  pgadmin:
    image: dpage/pgadmin4
    container_name: contrato_pgadmin
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
volumes:
  postgres_data:
